#!/usr/bin/env python3
from __future__ import annotations
import csv, hashlib, json, math, random, shutil, subprocess, sys, textwrap, zipfile
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from statistics import mean

HERE=Path(__file__).resolve().parent
BUILD=HERE/'build'; PKG=BUILD/'FINAL_QM28'; FD=PKG/'figure_data'; PC=PKG/'plot_code'; FG=PKG/'figures'; AC=PKG/'analysis_code'; TS=PKG/'tests'
SEED=280713; NOW=datetime.now(timezone.utc).isoformat()
def shab(b): return hashlib.sha256(b).hexdigest()
def shat(s): return shab(s.encode())
def uid(p,*x): return p+'_'+shat('|'.join(map(str,x)))[:20]
def wt(p,s): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(s.rstrip()+'\n',encoding='utf-8')
def wj(p,o): wt(p,json.dumps(o,ensure_ascii=False,indent=2,sort_keys=True))
def wc(p,fields,rows):
 p.parent.mkdir(parents=True,exist_ok=True)
 with p.open('w',encoding='utf-8',newline='') as f:
  w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore'); w.writeheader(); [w.writerow({k:r.get(k,'') for k in fields}) for r in rows]

def lr(a,b): return math.log(b/a) if a>0 and b>0 else ''
def pc(a,b): return 100*(b/a-1) if a else ''
P18='paper_10_1007_s11431_018_9323_3'; P24='paper_10_1016_j_msea_2023_145888'; P21='paper_10_1016_j_jmapro_2021_08_063'; P15='paper_10_1016_j_matdes_2015_07_058'
sources=[
 {'input_id':'SRC_2024_MSEA','locator':'File Library: 1593_as-rolled_TiB_TA15-Si_heat-treatment.pdf','kind':'PRIMARY_FULLTEXT_PDF','opened_status':'OPENED_FULLTEXT','doi':'10.1016/j.msea.2023.145888','title':'Microstructure evolution and enhanced mechanical properties of as-rolled TiB/(TA15-Si) composite via heat treatment','source_hash':shat('10.1016/j.msea.2023.145888|pages1-10|2026-07-13'),'hash_type':'NORMALIZED_EVIDENCE_CAPTURE_SHA256','priority':4,'use':'sequence, microstructure, hardness, 600/700C tensile pairs','notes':'Original byte hash unavailable; requested from local absorber.'},
 {'input_id':'SRC_2018_SCITECH','locator':'File Library: 0784_TiBw_near-alpha_heat-treatments.pdf','kind':'PRIMARY_FULLTEXT_PDF','opened_status':'OPENED_FULLTEXT','doi':'10.1007/s11431-018-9323-3','title':'Evolution of microstructure and high temperature tensile properties of as-extruded TiBw reinforced near-alpha titanium matrix composite subjected to heat treatments','source_hash':shat('10.1007/s11431-018-9323-3|pages1-6|2026-07-13'),'hash_type':'NORMALIZED_EVIDENCE_CAPTURE_SHA256','priority':4,'use':'Table 1 routes and Table 2 600C UTS/elongation pairs','notes':'Table 1 is authority over conflicting Figure 2 caption.'},
 {'input_id':'SRC_2021_JMAPRO','locator':'File Library: 1524_1526_TiB_Ti64_LPBF_creep.pdf','kind':'PRIMARY_FULLTEXT_PDF','opened_status':'OPENED_FULLTEXT','doi':'10.1016/j.jmapro.2021.08.063','title':'TiB reinforced Ti-6Al-4V matrix composites with improved short-term creep performance fabricated by laser powder bed fusion','source_hash':shat('10.1016/j.jmapro.2021.08.063|pages1-15|2026-07-13'),'hash_type':'NORMALIZED_EVIDENCE_CAPTURE_SHA256','priority':4,'use':'2x2 HT x reinforcement creep interaction','notes':'Table 2 5.8 h adjudicated over one 5.9 h body-text occurrence.'},
 {'input_id':'SRC_2015_MATDES','locator':'TITMC_V27_LIT_WEB_P009_OF_010.zip::fed57cf5_fed57cf5ba75312c.xml','kind':'PRIMARY_XML_INDEX_ENTRY','opened_status':'OPENED_INDEX_ONLY','doi':'10.1016/j.matdes.2015.07.058','title':'Effects of heat treatments on microstructure and tensile properties of as-extruded TiBw/near-alpha Ti composites','source_hash':'fed57cf5ba75312c691092603ebcd9a6210176f91b68a31d14de3fe54886412e','hash_type':'ORIGINAL_XML_SHA256','priority':4,'use':'scope anchor and exclusion audit','notes':'No resolved untreated comparator/full sequence in opened excerpt.'}]
archives=['00_统一上传总控与校验信息_20260712.zip','S02_PLATFORM_CORE_WEB_RETURN_PLOT_CODE_450_500MB_20260712.zip','S03_CODEX_ML_DATA_FEATURES_01_450_500MB_20260712.zip','S03_CODEX_ML_DATA_FEATURES_02_450_500MB_20260712.zip']+[f'S03_CODEX_ML_HARNESS_EVIDENCE_{i:02d}_450_500MB_20260712.zip' for i in range(1,9)]+['S04_GITHUB_HISTORY_STAGING_01_450_500MB_20260712.zip']+[f'S04_GITHUB_STAGING_CODE_{i:02d}_450_500MB_20260712.zip' for i in range(1,4)]+[f'TITMC_V27_LIT_WEB_P{i:03d}_OF_010.zip' for i in range(1,11)]
for n in archives: sources.append({'input_id':uid('ARCH',n),'locator':'/mnt/data/'+n,'kind':'UPLOADED_ARCHIVE','opened_status':'DISCOVERED_NOT_BYTE_OPENED','doi':'','title':n,'source_hash':'','hash_type':'MISSING_DUE_EXECUTION_SESSION_CAP','priority':1 if n.startswith(('00_','S03')) else 4,'use':'canonical source pending reducer','notes':'Visible attachment path; byte session rejected. Not credited as used.'})
SNAP='QM28_WEB_DERIVED_'+shat('\n'.join(sorted(f"{s['input_id']}|{s['source_hash']}|{s['opened_status']}" for s in sources)))[:20]
ph={P24:sources[0]['source_hash'],P18:sources[1]['source_hash'],P21:sources[2]['source_hash'],P15:sources[3]['source_hash']}

seq=[]
def sq(id,p,fam,base,purpose,t1,m1,c1,rel,t2='',m2='',c2='',db='',loc=''):
 seq.append({'sequence_uid':id,'paper_uid':p,'sample_family':fam,'baseline_state':base,'purpose':purpose,'stage_count':2 if t2!='' else 1,'stage_1_type':'solution' if purpose!='supertransus_isotropization' else 'solution_anneal','stage_1_temperature_C':t1,'stage_1_time_min':m1,'stage_1_cooling':c1,'stage_1_beta_transus_relation':rel,'stage_1_delta_beta_C':db,'stage_2_type':'aging' if t2!='' else '','stage_2_temperature_C':t2,'stage_2_time_min':m2,'stage_2_cooling':c2,'sequence_canonical':f'{t1}C/{m1}min/{c1}'+(f' -> {t2}C/{m2}min/{c2}' if t2!='' else ''),'evidence_level':'DIRECT_TABLE_TEXT' if p==P18 else 'DIRECT_TEXT','source_locator':loc,'support_domain':fam})
sq('HTSEQ_2018_HT1',P18,'5.1vol%TiBw_near-alpha_PM_extruded','as-extruded','solution_plus_aging',1100,120,'AC','supertransus_single_beta_field',500,300,'AC',loc='2018 Table 1')
for h,t in [('HT2',500),('HT3',600),('HT4',700)]: sq('HTSEQ_2018_'+h,P18,'5.1vol%TiBw_near-alpha_PM_extruded','as-extruded','solution_plus_aging',1000,120,'AC','subtransus_alpha_plus_beta_field',t,300,'AC',loc='2018 Table 1')
for t in [550,600,650,700,750]: sq(f'HTSEQ_2024_1050WQ_{t}AC',P24,'3.5vol%TiB_TA15_0.3wtSi_hot-rolled','as-rolled','beta_solution_plus_aging',1050,30,'WQ','supertransus_beta_field',t,60,'AC',30,'2024 Sections 2.1-2.2')
sq('HTSEQ_2024_1050WQ_ONLY',P24,'3.5vol%TiB_TA15_0.3wtSi_hot-rolled','as-rolled','beta_solution',1050,30,'WQ','supertransus_beta_field',db=30,loc='2024 Section 2.2')
sq('HTSEQ_2021_SUPERTRANSUS_FC',P21,'LPBF_Ti64_and_TiB-Ti64','as-built','supertransus_isotropization',1050,120,'FC','supertransus',loc='2021 Section 2')

obs=[]
def ob(p,s,c,q,m,r,proc,micro,mode,temp,stress,rate,ori,prop,val,unit,ev,loc,n=''):
 obs.append({'record_uid':uid('REC',p,s,c,prop,val),'snapshot_id':SNAP,'paper_uid':p,'sample_uid':s,'condition_uid':c,'sequence_uid':q,'matrix':m,'reinforcement':r,'process':proc,'microstructure_state':micro,'test_mode':mode,'test_temperature_C':temp,'stress_MPa':stress,'strain_rate_s_1':rate,'orientation':ori,'property':prop,'value':val,'unit':unit,'reported_n':n,'reported_uncertainty':'','evidence_level':ev,'source_locator':loc,'source_hash':ph[p]})
# 2018 direct Table 2
v18={'UNTREATED':('',850,15.5,'lamellar alpha+beta; deformation substructure'),'HT1':('HTSEQ_2018_HT1',904,14.5,'fine transformed beta; no alpha2/silicide at 500C'),'HT2':('HTSEQ_2018_HT2',953,14.0,'primary alpha+transformed beta; fine alpha2'),'HT3':('HTSEQ_2018_HT3',955,13.2,'primary alpha+transformed beta; alpha2 growth'),'HT4':('HTSEQ_2018_HT4',986,10.8,'alpha2 20-30 nm; TiB stable')}
for k,(q,u,e,mi) in v18.items():
 c=uid('COND',P18,k,600,'tension')
 for prop,val,un in [('UTS',u,'MPa'),('elongation',e,'%')]: ob(P18,'S2018_'+k,c,q,'near-alpha Ti-5.8Al-3.4Zr-4Sn-0.4Mo-0.4Nb-0.4Si-0.06C','5.1 vol% TiBw','PM+hot extrusion',mi,'tension',600,'',5.6e-3,'extrusion direction',prop,val,un,'DIRECT_TABLE_TEXT','Table 2')
# 2024 hardness and tensile
hv=[('AS_ROLLED','',422,'kinked alpha+beta lamella; 200-300 nm silicides'),('SOLUTION','HTSEQ_2024_1050WQ_ONLY',444,'alpha-prime martensite; silicides dissolved; prior beta ~47um'),('AGE550','HTSEQ_2024_1050WQ_550AC',475,'martensite retained; weak alpha2'),('AGE600','HTSEQ_2024_1050WQ_600AC',482,'martensite; silicides at prior-beta/TiB; weak alpha2'),('AGE650','HTSEQ_2024_1050WQ_650AC',455,'martensite decomposition begins; alpha+beta'),('AGE700','HTSEQ_2024_1050WQ_700AC',440,'acicular alpha+beta; more silicides'),('AGE750','HTSEQ_2024_1050WQ_750AC',413,'complete decomposition; abnormal alpha growth')]
for k,q,v,mi in hv: ob(P24,'S2024_'+k,uid('COND',P24,k,'hardness'),q,'TA15+0.3wt%Si','3.5 vol% TiB','hot pressing+80% hot rolling',mi,'microhardness',25,'','','','microhardness',v,'HV','DIRECT_FIGURE_LABEL','Figure 8a',5)
tens=[('AS_ROLLED','',600,710,39,'rolled alpha+beta/silicides'),('AGE600','HTSEQ_2024_1050WQ_600AC',600,992,26,'martensite+silicides+weak alpha2'),('AGE700','HTSEQ_2024_1050WQ_700AC',600,852,32,'acicular alpha+beta+silicides'),('AGE750','HTSEQ_2024_1050WQ_750AC',600,768,None,'abnormal alpha growth'),('AS_ROLLED','',700,228,182,'rolled refined microstructure'),('AGE600','HTSEQ_2024_1050WQ_600AC',700,399,68,'service-induced decomposition/silicides'),('AGE700','HTSEQ_2024_1050WQ_700AC',700,421,68,'alpha+beta/more silicides')]
for k,q,t,u,e,mi in tens:
 c=uid('COND',P24,k,t,'tension'); ob(P24,'S2024_'+k,c,q,'TA15+0.3wt%Si','3.5 vol% TiB','hot pressing+80% hot rolling',mi,'tension',t,'','','rolling direction','UTS',u,'MPa','DIRECT_TEXT_AND_CURVE','Sections 3.3/Figure 8b',3)
 if e is not None: ob(P24,'S2024_'+k,c,q,'TA15+0.3wt%Si','3.5 vol% TiB','hot pressing+80% hot rolling',mi,'tension',t,'','','rolling direction','elongation',e,'%','DIRECT_TEXT','Section 3.3',3)
# 2021 Table 2
cr=[('AB_TI64','','none',3.4,5.93,28.3,53.3,'columnar prior beta+alpha-prime'),('AB_TMC','','TiB from 0.2wt%B4C',2.9,4.48,13.26,66.7,'columnar prior beta+fine TiB/alpha-prime'),('HT_TI64','HTSEQ_2021_SUPERTRANSUS_FC','none',0.6,2.16,3.6,None,'prior beta 257+/-83um+continuous GB-alpha 11.2+/-3.3um'),('HT_TMC','HTSEQ_2021_SUPERTRANSUS_FC','TiB from 0.2wt%B4C',5.8,0.84,7.46,12.5,'equiaxed alpha 5.75+/-1.6um; no continuous GB-alpha; coarsened TiB')]
for k,q,r,tr,rate,total,e5,mi in cr:
 c=uid('COND',P21,k,600,200,'creep')
 for prop,val,un in [('creep_rupture_time',tr,'h'),('steady_state_creep_rate',rate,'%/h'),('total_creep_strain',total,'%'),('5D_elongation',e5,'%')]:
  if val is not None: ob(P21,'S2021_'+k,c,q,'Ti64',r,'LPBF',mi,'constant-load creep tension',600,200,'','build/loading direction',prop,val,un,'DIRECT_TABLE_TEXT','Table 2')

idx={(r['paper_uid'],r['sample_uid'],r['property'],r['test_temperature_C']):r for r in obs}; pairs=[]
def pair(b,t,note,des='higher'):
 pairs.append({'pair_uid':uid('PAIR',b['record_uid'],t['record_uid']),'snapshot_id':SNAP,'paper_uid':b['paper_uid'],'baseline_record_uid':b['record_uid'],'treated_record_uid':t['record_uid'],'baseline_sample_uid':b['sample_uid'],'treated_sample_uid':t['sample_uid'],'baseline_condition_uid':b['condition_uid'],'treated_condition_uid':t['condition_uid'],'sequence_uid':t['sequence_uid'],'property':b['property'],'unit':b['unit'],'test_mode':b['test_mode'],'test_temperature_C':b['test_temperature_C'],'baseline_value':b['value'],'treated_value':t['value'],'delta':t['value']-b['value'],'lnRR':lr(b['value'],t['value']),'percent_change':pc(b['value'],t['value']),'desirability_direction':des,'match_class':'A','matched_fields':'paper,matrix,reinforcement,process,test_mode,test_temperature,orientation','mismatch_fields':'heat_treatment_only','evidence_level':t['evidence_level'],'uncertainty_status':'NOT_REPORTED_AT_EFFECT_LEVEL','claim_level':2,'support_domain':t['process']+'; '+t['matrix']+'; '+t['reinforcement'],'pair_note':note,'source_locator':t['source_locator'],'source_hash':t['source_hash']})
for prop in ['UTS','elongation']:
 b=idx[(P18,'S2018_UNTREATED',prop,600)]
 for h in ['HT1','HT2','HT3','HT4']: pair(b,idx[(P18,'S2018_'+h,prop,600)],h+' vs untreated')
b=idx[(P24,'S2024_AS_ROLLED','microhardness',25)]
for h in ['SOLUTION','AGE550','AGE600','AGE650','AGE700','AGE750']: pair(b,idx[(P24,'S2024_'+h,'microhardness',25)],h+' vs as-rolled')
for t in [600,700]:
 for prop in ['UTS','elongation']:
  b=idx[(P24,'S2024_AS_ROLLED',prop,t)]
  for x in [r for r in obs if r['paper_uid']==P24 and r['property']==prop and r['test_temperature_C']==t and r['sample_uid']!='S2024_AS_ROLLED']: pair(b,x,x['sample_uid']+' vs as-rolled')
for z in ['TI64','TMC']:
 for prop in ['creep_rupture_time','steady_state_creep_rate','total_creep_strain','5D_elongation']:
  kb=(P21,'S2021_AB_'+z,prop,600); kt=(P21,'S2021_HT_'+z,prop,600)
  if kb in idx and kt in idx: pair(idx[kb],idx[kt],'HT vs as-built '+z,'lower' if prop=='steady_state_creep_rate' else 'context_dependent' if prop=='total_creep_strain' else 'higher')

effects=[{'effect_uid':uid('EFFECT',p['pair_uid']),'snapshot_id':SNAP,'pair_uid':p['pair_uid'],'paper_uid':p['paper_uid'],'estimand':'HT_vs_baseline_same_material_condition','property':p['property'],'unit':p['unit'],'baseline_value':p['baseline_value'],'treated_value':p['treated_value'],'delta':p['delta'],'lnRR':p['lnRR'],'percent_change':p['percent_change'],'ci_low':'','ci_high':'','prediction_low':'','prediction_high':'','uncertainty_method':'not estimable: replicate SD/SE absent','independent_papers':1,'samples':2,'evidence_level':p['evidence_level'],'support_domain':p['support_domain'],'claim_level':2,'status':'IDENTIFIED_POINT_ONLY','source_hash':p['source_hash'],'source_locator':p['source_locator']} for p in pairs]
kp=[p for p in pairs if p['property']=='UTS' and p['test_temperature_C']==600]; pm=defaultdict(list)
for p in kp: pm[p['paper_uid']].append(float(p['delta']))
pm={k:mean(v) for k,v in pm.items()}; eq=mean(pm.values()); pw=mean([float(p['delta']) for p in kp]); random.seed(SEED); ks=sorted(pm); bt=sorted(mean(pm[random.choice(ks)] for _ in ks) for _ in range(20000)); lo=bt[int(.025*(len(bt)-1))]; hi=bt[int(.975*(len(bt)-1))]
for id,est,method,status in [('SUMMARY_UTS600_EQUAL_PAPER',eq,'paper-cluster bootstrap 20000 draws, k=2; discrete/exploratory','EXPLORATORY_K2'),('SUMMARY_UTS600_PAIR_WEIGHTED',pw,'descriptive only','DESCRIPTIVE')]: effects.append({'effect_uid':id,'snapshot_id':SNAP,'pair_uid':'','paper_uid':'MULTI_PAPER','estimand':'paper_equal_mean_delta_UTS_600C' if id.endswith('PAPER') else 'pair_weighted_mean_delta_UTS_600C','property':'UTS','unit':'MPa','baseline_value':'','treated_value':'','delta':est,'lnRR':'','percent_change':'','ci_low':lo if id.endswith('PAPER') else '','ci_high':hi if id.endswith('PAPER') else '','prediction_low':'','prediction_high':'','uncertainty_method':method,'independent_papers':2,'samples':14,'evidence_level':'DIRECT_TABLE_TEXT','support_domain':'two near-alpha TiBw families; 600C tension','claim_level':2 if id.endswith('PAPER') else 1,'status':status,'source_hash':shat(ph[P18]+ph[P24]),'source_locator':'2018 Table 2 + 2024 Section 3.3'})
hier=[{'result_id':'HIER_UTS600_EQUAL_PAPER','outcome':'UTS','test_temperature_C':600,'model':'paper-equal descriptive meta-summary + paper-cluster bootstrap','estimate':eq,'unit':'MPa','ci_low':lo,'ci_high':hi,'prediction_low':'','prediction_high':'','status':'EXPLORATORY_K2_NOT_HIERARCHICALLY_IDENTIFIABLE','independent_papers':2,'matched_pairs':len(kp),'tau2':'NOT_IDENTIFIABLE','I2':'NOT_IDENTIFIABLE','notes':'Discrete cluster support; no random-effects/prediction interval claim.'},{'result_id':'HIER_FORMAL_RANDOM_EFFECTS','outcome':'all','test_temperature_C':'','model':'random intercept/random slope','estimate':'','unit':'','ci_low':'','ci_high':'','prediction_low':'','prediction_high':'','status':'NOT_IDENTIFIABLE','independent_papers':3,'matched_pairs':len(pairs),'tau2':'','I2':'','notes':'Outcomes/process families/purposes/cooling paths non-commensurate.'}]
# Dose rows
dose=[]
for p in pairs:
 s=next((x for x in seq if x['sequence_uid']==p['sequence_uid']),None)
 if s and s['stage_2_temperature_C']!='' and p['property'] in ['UTS','elongation','microhardness']: dose.append({'dose_uid':uid('DOSE',p['pair_uid']),'paper_uid':p['paper_uid'],'sequence_uid':p['sequence_uid'],'property':p['property'],'unit':p['unit'],'test_temperature_C':p['test_temperature_C'],'solution_temperature_C':s['stage_1_temperature_C'],'solution_time_min':s['stage_1_time_min'],'solution_cooling':s['stage_1_cooling'],'beta_transus_relation':s['stage_1_beta_transus_relation'],'delta_beta_C':s['stage_1_delta_beta_C'],'aging_temperature_C':s['stage_2_temperature_C'],'aging_time_min':s['stage_2_time_min'],'aging_cooling':s['stage_2_cooling'],'delta_effect':p['delta'],'lnRR':p['lnRR'],'percent_change':p['percent_change'],'support_status':'OBSERVED_ONLY','model_status':'NO_EXTRAPOLATION','evidence_level':p['evidence_level'],'source_locator':p['source_locator']})
dsum=[{'result_id':'DOSE_2018','paper_uid':P18,'property':'UTS','test_temperature_C':600,'route':'1000C/120min/AC + age 500-700C/300min/AC','observed_aging_range_C':'500-700','endpoint_slope':(136-103)/200,'slope_unit':'MPa/C','shape':'increasing over observed endpoints','status':'DESCRIPTIVE_WITHIN_ROUTE','notes':'alpha2 state not separable from aging temperature.'},{'result_id':'DOSE_2024','paper_uid':P24,'property':'UTS','test_temperature_C':600,'route':'1050C/30min/WQ + age 600-750C/60min/AC','observed_aging_range_C':'600-750','endpoint_slope':(58-282)/150,'slope_unit':'MPa/C','shape':'decreasing after 600C optimum','status':'DESCRIPTIVE_WITHIN_ROUTE','notes':'martensite decomposition/abnormal alpha growth dominate.'},{'result_id':'DOSE_GENERAL','paper_uid':'MULTI_PAPER','property':'UTS','test_temperature_C':'600/700','route':'temperature-time-cooling','observed_aging_range_C':'500-750','endpoint_slope':'','slope_unit':'','shape':'route-dependent sign reversal','status':'NOT_IDENTIFIABLE','notes':'time/cooling/matrix/process/solution state confounded.'}]
# Interactions
D={k:(tr,ra) for k,q,r,tr,ra,total,e5,mi in cr}; did=(D['HT_TMC'][0]-D['AB_TMC'][0])-(D['HT_TI64'][0]-D['AB_TI64'][0]); ror=(D['HT_TMC'][0]/D['AB_TMC'][0])/(D['HT_TI64'][0]/D['AB_TI64'][0]); didr=(D['HT_TMC'][1]-D['AB_TMC'][1])-(D['HT_TI64'][1]-D['AB_TI64'][1]); rorr=(D['HT_TMC'][1]/D['AB_TMC'][1])/(D['HT_TI64'][1]/D['AB_TI64'][1])
ints=[{'interaction_uid':'INT_2021_RUPTURE','paper_uid':P21,'estimand':'difference_in_differences','outcome':'creep_rupture_time','unit':'h','matrix_ht_effect':-2.8,'tmc_ht_effect':2.9,'additive_interaction':did,'ratio_of_ratios':ror,'log_ratio_of_ratios':math.log(ror),'ci_low':'','ci_high':'','uncertainty_status':'NOT_IDENTIFIABLE_REPLICATE_VARIANCE_ABSENT','match_class':'A_WITHIN_PAPER_2X2','claim_level':2,'interpretation':'Sign reversal: Ti64 rupture collapses while TiB/Ti64 doubles.','mechanism':'continuous GB-alpha in Ti64 vs suppression/equiaxed alpha/interfaces/load transfer in TMC','source_locator':'2021 Table 2 and Sections 3-5'},{'interaction_uid':'INT_2021_RATE','paper_uid':P21,'estimand':'difference_in_differences','outcome':'steady_state_creep_rate','unit':'%/h','matrix_ht_effect':D['HT_TI64'][1]-D['AB_TI64'][1],'tmc_ht_effect':D['HT_TMC'][1]-D['AB_TMC'][1],'additive_interaction':didr,'ratio_of_ratios':rorr,'log_ratio_of_ratios':math.log(rorr),'ci_low':'','ci_high':'','uncertainty_status':'NOT_IDENTIFIABLE_REPLICATE_VARIANCE_ABSENT','match_class':'A_WITHIN_PAPER_2X2','claim_level':2,'interpretation':'Both rates fall; decisive interaction is rupture path.','mechanism':'GB-alpha failure-path effect is orthogonal to rate reduction','source_locator':'2021 Table 2'}]
het=[{'heterogeneity_id':'HET_AGING_SIGN','factor':'matrix/process/sequence','strata':'2018 extruded vs 2024 rolled','outcome':'UTS delta at 600C','range_or_contrast':'2018 +103 to +136 MPa; 2024 +282 to +58 MPa after optimum','status':'OBSERVED_EFFECT_MODIFICATION','interpretation':'No portable aging-temperature main effect.'},{'heterogeneity_id':'HET_REINFORCEMENT','factor':'TiB reinforcement','strata':'LPBF Ti64 vs TiB/Ti64','outcome':'HT rupture-time effect','range_or_contrast':'-2.8 vs +2.9 h; DID +5.7 h','status':'STRONG_WITHIN_PAPER_INTERACTION_POINT_ESTIMATE','interpretation':'Matrix-only HT optimization is unsafe.'},{'heterogeneity_id':'HET_FORMAL','factor':'paper random effects','strata':'all','outcome':'all','range_or_contrast':'','status':'NOT_IDENTIFIABLE','interpretation':'Only three independent quantitative papers/non-commensurate outcomes.'}]
sens=[]
for om in ks:
 e=mean(v for k,v in pm.items() if k!=om); sens.append({'sensitivity_id':uid('SENS','LOPO',om),'analysis':'leave_one_paper_out','target':'paper-equal delta UTS at 600C','omitted':om,'estimate':e,'unit':'MPa','reference_estimate':eq,'absolute_shift':abs(e-eq),'relative_shift_percent':100*abs(e-eq)/abs(eq),'status':'HIGH_SENSITIVITY_K2','notes':'Equivalent to leave-family-out.'})
sens += [{'sensitivity_id':'SENS_WEIGHTING','analysis':'paper_equal_vs_pair_weighted','target':'delta UTS at 600C','omitted':'','estimate':pw,'unit':'MPa','reference_estimate':eq,'absolute_shift':abs(pw-eq),'relative_shift_percent':100*abs(pw-eq)/eq,'status':'MODEST_WEIGHTING_SHIFT','notes':'Pair weighting overweights four-route paper.'},{'sensitivity_id':'SENS_MISSING_EL750','analysis':'complete_case','target':'2024 elongation response','omitted':'750C aging','estimate':'','unit':'%','reference_estimate':'','absolute_shift':'','relative_shift_percent':'','status':'NOT_IDENTIFIABLE','notes':'No direct exact value; no imputation/digitization.'},{'sensitivity_id':'SENS_2015','analysis':'source_exclusion','target':'pooled HT effect','omitted':P15,'estimate':eq,'unit':'MPa','reference_estimate':eq,'absolute_shift':0,'relative_shift_percent':0,'status':'EXCLUDED_A_PRIORI','notes':'Index excerpt lacks comparator/sequence.'}]
neg=[{'result_id':'NEG_2018_EL','paper_uid':P18,'condition':'four solution+aging routes, 600C tension','outcome':'elongation','observation':'All routes reduce elongation by 1.0-4.7 percentage points.','interpretation':'Strength gain is purchased with ductility loss.','evidence_level':'DIRECT_TABLE_TEXT'},{'result_id':'NEG_2024_OVERAGE','paper_uid':P24,'condition':'1050C/WQ+750C/1h/AC','outcome':'hardness/600C UTS','observation':'413 HV is 9 HV below as-rolled; UTS gain shrinks to +58 MPa.','interpretation':'Decomposition/abnormal alpha growth defeat precipitation gains.','evidence_level':'DIRECT_FIGURE_LABEL_AND_TEXT'},{'result_id':'NEG_2024_EL','paper_uid':P24,'condition':'1050C/WQ+600-700C aging','outcome':'elongation','observation':'600C: 39% to 26-32%; 700C: 182% to 68%.','interpretation':'Strength retention does not imply ductility retention.','evidence_level':'DIRECT_TEXT'},{'result_id':'NEG_2021_TI64','paper_uid':P21,'condition':'Ti64 1050C/2h/FC','outcome':'creep rupture time','observation':'3.4 to 0.6 h (-82.35%).','interpretation':'Continuous GB-alpha creates a fast crack path.','evidence_level':'DIRECT_TABLE_TEXT'},{'result_id':'NULL_GENERAL','paper_uid':'MULTI_PAPER','condition':'missing canonical beta-transus/cooling/variance','outcome':'portable HT coefficient','observation':'NOT_IDENTIFIABLE','interpretation':'Claim ceiling remains route-specific paired association.','evidence_level':'UNRESOLVED'}]
conf=[{'conflict_id':'C001','paper_uid':P18,'field':'HT2 aging temperature','value_a':'500C/5h Table 1','value_b':'550C/5h Figure 2 caption','adjudication':'Use Table 1/Table 2 labels.','status':'OPEN_SOURCE_INTERNAL_CONFLICT','impact':'Micrograph route label uncertainty; property pairing retained.'},{'conflict_id':'C002','paper_uid':P21,'field':'HT-TMC rupture time','value_a':'5.8 h Table 2/abstract/conclusion','value_b':'5.9 h one body passage','adjudication':'Use Table 2 5.8 h.','status':'RESOLVED_BY_TABLE_AUTHORITY','impact':'DID +5.7 h, not +5.8 h.'},{'conflict_id':'C003','paper_uid':P24,'field':'700C strength mechanism wording','value_a':'more silicides','value_b':'decrease in dislocation density','adjudication':'Numeric result retained; mechanism downgraded.','status':'OPEN_MECHANISM_WORDING_CONFLICT','impact':'No numeric change.'},{'conflict_id':'C004','paper_uid':P15,'field':'pairing eligibility','value_a':'aged UTS indexed','value_b':'baseline/full route absent','adjudication':'Exclude.','status':'OPEN_DATA_GAP','impact':'Relevant paper not in quantitative cohort.'}]
cohort=[{'paper_uid':P18,'doi':'10.1007/s11431-018-9323-3','title':sources[1]['title'],'matrix':'near-alpha Ti','reinforcement':'5.1 vol% TiBw','process':'PM+hot extrusion','sample_uid':'S2018_FAMILY','cohort_role':'paired tensile/dose','included':1,'exclusion_reason':'','source_hash':ph[P18]},{'paper_uid':P24,'doi':'10.1016/j.msea.2023.145888','title':sources[0]['title'],'matrix':'TA15+Si','reinforcement':'3.5 vol% TiB','process':'hot pressing+rolling','sample_uid':'S2024_FAMILY','cohort_role':'hardness/tensile/dose','included':1,'exclusion_reason':'','source_hash':ph[P24]},{'paper_uid':P21,'doi':'10.1016/j.jmapro.2021.08.063','title':sources[2]['title'],'matrix':'Ti64','reinforcement':'none vs TiB','process':'LPBF','sample_uid':'S2021_2X2','cohort_role':'HTxreinforcement creep','included':1,'exclusion_reason':'','source_hash':ph[P21]},{'paper_uid':P15,'doi':'10.1016/j.matdes.2015.07.058','title':sources[3]['title'],'matrix':'near-alpha Ti','reinforcement':'TiBw','process':'extruded','sample_uid':'','cohort_role':'scope anchor','included':0,'exclusion_reason':'index-only; no resolved comparator/full route','source_hash':ph[P15]}]
excl=[{'excluded_uid':'EXC_2015','paper_uid':P15,'doi':'10.1016/j.matdes.2015.07.058','reason_code':'NO_RESOLVED_BASELINE_SEQUENCE','details':'Only evidence-index excerpt opened.','required_to_include':'full XML route/baseline/property/provenance extraction'},{'excluded_uid':'EXC_2024_EL750','paper_uid':P24,'doi':'10.1016/j.msea.2023.145888','reason_code':'EXACT_VALUE_NOT_DIRECTLY_REPORTED','details':'Curve only; no digitization.','required_to_include':'validated axis-calibrated digitization'}]

def build():
 if BUILD.exists(): shutil.rmtree(BUILD)
 for d in [PKG,FD,PC,FG,AC,TS]: d.mkdir(parents=True,exist_ok=True)
 wt(PKG/'OPENED_FILES.txt','WINDOW=QM28 | SNAPSHOT='+SNAP+' | INPUT_MODE=QUANT_EXECUTE/COHORT_BUILD\n\nACTUALLY OPENED:\n'+'\n'.join(f"- [{s['opened_status']}] {s['locator']} | {s['doi']} | {s['source_hash']} ({s['hash_type']})" for s in sources if s['opened_status'].startswith('OPENED'))+'\n\nDISCOVERED BUT NOT BYTE-OPENED:\n'+'\n'.join('- '+s['locator'] for s in sources if s['opened_status']=='DISCOVERED_NOT_BYTE_OPENED'))
 wc(PKG/'INPUT_LEDGER.csv',['input_id','locator','kind','opened_status','doi','title','source_hash','hash_type','priority','use','notes'],sources)
 wc(PKG/'ANALYSIS_COHORT.csv',['paper_uid','doi','title','matrix','reinforcement','process','sample_uid','cohort_role','included','exclusion_reason','source_hash'],cohort)
 wc(PKG/'EXCLUDED_RECORDS.csv',['excluded_uid','paper_uid','doi','reason_code','details','required_to_include'],excl)
 sf=['sequence_uid','paper_uid','sample_family','baseline_state','purpose','stage_count','stage_1_type','stage_1_temperature_C','stage_1_time_min','stage_1_cooling','stage_1_beta_transus_relation','stage_1_delta_beta_C','stage_2_type','stage_2_temperature_C','stage_2_time_min','stage_2_cooling','sequence_canonical','evidence_level','source_locator','support_domain']; wc(PKG/'HEAT_TREATMENT_SEQUENCES.csv',sf,seq)
 of=['record_uid','snapshot_id','paper_uid','sample_uid','condition_uid','sequence_uid','matrix','reinforcement','process','microstructure_state','test_mode','test_temperature_C','stress_MPa','strain_rate_s_1','orientation','property','value','unit','reported_n','reported_uncertainty','evidence_level','source_locator','source_hash']; wc(PKG/'ATOMIC_COHORT_RECORDS.csv',of,obs)
 pf=['pair_uid','snapshot_id','paper_uid','baseline_record_uid','treated_record_uid','baseline_sample_uid','treated_sample_uid','baseline_condition_uid','treated_condition_uid','sequence_uid','property','unit','test_mode','test_temperature_C','baseline_value','treated_value','delta','lnRR','percent_change','desirability_direction','match_class','matched_fields','mismatch_fields','evidence_level','uncertainty_status','claim_level','support_domain','pair_note','source_locator','source_hash']; wc(PKG/'PAIR_MATCHES.csv',pf,pairs); wc(PKG/'HT_PAIR_EFFECTS.csv',pf,pairs)
 ef=['effect_uid','snapshot_id','pair_uid','paper_uid','estimand','property','unit','baseline_value','treated_value','delta','lnRR','percent_change','ci_low','ci_high','prediction_low','prediction_high','uncertainty_method','independent_papers','samples','evidence_level','support_domain','claim_level','status','source_hash','source_locator']; wc(PKG/'EFFECT_ESTIMATES.csv',ef,effects)
 wc(PKG/'HIERARCHICAL_RESULTS.csv',['result_id','outcome','test_temperature_C','model','estimate','unit','ci_low','ci_high','prediction_low','prediction_high','status','independent_papers','matched_pairs','tau2','I2','notes'],hier)
 df=['dose_uid','paper_uid','sequence_uid','property','unit','test_temperature_C','solution_temperature_C','solution_time_min','solution_cooling','beta_transus_relation','delta_beta_C','aging_temperature_C','aging_time_min','aging_cooling','delta_effect','lnRR','percent_change','support_status','model_status','evidence_level','source_locator']; wc(PKG/'HT_DOSE_RESPONSE.csv',df,dose); wc(PKG/'DOSE_RESPONSE.csv',['result_id','paper_uid','property','test_temperature_C','route','observed_aging_range_C','endpoint_slope','slope_unit','shape','status','notes'],dsum)
 inf=['interaction_uid','paper_uid','estimand','outcome','unit','matrix_ht_effect','tmc_ht_effect','additive_interaction','ratio_of_ratios','log_ratio_of_ratios','ci_low','ci_high','uncertainty_status','match_class','claim_level','interpretation','mechanism','source_locator']; wc(PKG/'INTERACTION_EFFECTS.csv',inf,ints); wc(PKG/'HT_REINFORCEMENT_INTERACTIONS.csv',inf,ints)
 wc(PKG/'HETEROGENEITY.csv',['heterogeneity_id','factor','strata','outcome','range_or_contrast','status','interpretation'],het); wc(PKG/'SENSITIVITY_ANALYSIS.csv',['sensitivity_id','analysis','target','omitted','estimate','unit','reference_estimate','absolute_shift','relative_shift_percent','status','notes'],sens); wc(PKG/'NULL_NEGATIVE_RESULTS.csv',['result_id','paper_uid','condition','outcome','observation','interpretation','evidence_level'],neg); wc(PKG/'CONFLICT_LEDGER.csv',['conflict_id','paper_uid','field','value_a','value_b','adjudication','status','impact'],conf)
 with (PKG/'PROVENANCE.jsonl').open('w',encoding='utf-8') as f:
  for e in effects:
   p=next((x for x in pairs if x['pair_uid']==e['pair_uid']),None); f.write(json.dumps({'provenance_uid':uid('PROV',e['effect_uid']),'snapshot_id':SNAP,'paper_uid':e['paper_uid'],'sample_uid':p['treated_sample_uid'] if p else 'MULTI','condition_uid':p['treated_condition_uid'] if p else 'MULTI','effect_uid':e['effect_uid'],'source_hash':e['source_hash'],'source_hash_type':'NORMALIZED_EVIDENCE_CAPTURE_SHA256_OR_ORIGINAL_XML_SHA256','source_locator':e['source_locator'],'evidence_level':e['evidence_level'],'transformation':'same-paper subtraction; optional lnRR; no imputation','generated_at':NOW},ensure_ascii=False,sort_keys=True)+'\n')
  for s in seq: f.write(json.dumps({'provenance_uid':uid('PROVSEQ',s['sequence_uid']),'snapshot_id':SNAP,'paper_uid':s['paper_uid'],'sample_uid':s['sample_family'],'condition_uid':s['sequence_uid'],'effect_uid':'','source_hash':ph[s['paper_uid']],'source_hash_type':'NORMALIZED_EVIDENCE_CAPTURE_SHA256','source_locator':s['source_locator'],'evidence_level':s['evidence_level'],'transformation':'ordered sequence preserved; not collapsed','generated_at':NOW},ensure_ascii=False,sort_keys=True)+'\n')
 wc(PKG/'SOURCE_EVIDENCE_INDEX.csv',['input_id','doi','title','locator','source_hash','hash_type','opened_status','evidence_use','validation_note'],[{'input_id':s['input_id'],'doi':s['doi'],'title':s['title'],'locator':s['locator'],'source_hash':s['source_hash'],'hash_type':s['hash_type'],'opened_status':s['opened_status'],'evidence_use':s['use'],'validation_note':s['notes']} for s in sources[:4]])
 # Figure data
 nodes=[('N0',0,'As-extruded / as-rolled / as-built',3),('N1',1,'Subtransus solution + AC',1),('N2',1,'Supertransus solution + AC/WQ/FC',3),('N3',2,'Age 500-600 C',2),('N4',2,'Age 650-700 C',2),('N5',2,'Age 750 C',1),('N6',2,'No aging; furnace cool',1),('N7',3,'alpha2 / silicide strengthening',2),('N8',3,'martensite -> acicular alpha+beta',1),('N9',3,'abnormal alpha growth / overaging',1),('N10',3,'GB-alpha: present in Ti64, suppressed by TiB',1)]
 edges=[('N0','N1',3,'2018 HT2-HT4'),('N0','N2',7,'2018 HT1; 2024; 2021'),('N1','N3',2,'2018 500/600'),('N1','N4',1,'2018 700'),('N2','N3',3,'2018/2024'),('N2','N4',2,'2024'),('N2','N5',1,'2024'),('N2','N6',1,'2021'),('N3','N7',4,'alpha2/silicides'),('N4','N7',1,'2018 alpha2'),('N4','N8',2,'2024 decomposition'),('N5','N9',1,'2024 abnormal alpha'),('N6','N10',2,'2021 divergence')]
 wc(FD/'heat_treatment_path_nodes.csv',['node_id','stage','label','papers_n'],[dict(zip(['node_id','stage','label','papers_n'],x)) for x in nodes]); wc(FD/'heat_treatment_path_edges.csv',['source','target','weight','evidence'],[dict(zip(['source','target','weight','evidence'],x)) for x in edges])
 forest=[]
 for p in kp:
  s=next(x for x in seq if x['sequence_uid']==p['sequence_uid']); forest.append({'paper_uid':p['paper_uid'],'label':('2018 '+p['treated_sample_uid'].split('_')[-1]) if p['paper_uid']==P18 else ('2024 '+p['treated_sample_uid'].replace('S2024_','')),'aging_temperature_C':s['stage_2_temperature_C'],'aging_time_min':s['stage_2_time_min'],'solution_temperature_C':s['stage_1_temperature_C'],'cooling_path':s['stage_1_cooling']+'+'+s['stage_2_cooling'],'delta_UTS_MPa':p['delta'],'percent_change':p['percent_change'],'ci_low':'','ci_high':'','evidence':p['evidence_level'],'support':p['support_domain']})
 forest.append({'paper_uid':'MULTI_PAPER','label':'Paper-equal summary (k=2)','aging_temperature_C':'','aging_time_min':'','solution_temperature_C':'','cooling_path':'mixed','delta_UTS_MPa':eq,'percent_change':'','ci_low':lo,'ci_high':hi,'evidence':'DIRECT_TABLE_TEXT','support':'two families; exploratory bootstrap'})
 wc(FD/'ht_paired_forest.csv',['paper_uid','label','aging_temperature_C','aging_time_min','solution_temperature_C','cooling_path','delta_UTS_MPa','percent_change','ci_low','ci_high','evidence','support'],forest); wc(FD/'ttc_response_observations.csv',df,[r for r in dose if r['property'] in ['UTS','microhardness']]); interaction=[{'reinforcement':'Ti64 matrix','state':'As-built','rupture_time_h':3.4,'steady_state_rate_pct_h':5.93},{'reinforcement':'Ti64 matrix','state':'Heat-treated','rupture_time_h':0.6,'steady_state_rate_pct_h':2.16},{'reinforcement':'TiB/Ti64 TMC','state':'As-built','rupture_time_h':2.9,'steady_state_rate_pct_h':4.48},{'reinforcement':'TiB/Ti64 TMC','state':'Heat-treated','rupture_time_h':5.8,'steady_state_rate_pct_h':0.84}]; wc(FD/'ht_reinforcement_interaction.csv',['reinforcement','state','rupture_time_h','steady_state_rate_pct_h'],interaction)
 plots={
 'plot_heat_treatment_alluvial.py':'''import csv\nfrom pathlib import Path\nimport matplotlib.pyplot as plt\nfrom matplotlib.patches import FancyArrowPatch,FancyBboxPatch\nR=Path(__file__).resolve().parents[1]; ns=list(csv.DictReader((R/'figure_data/heat_treatment_path_nodes.csv').open())); es=list(csv.DictReader((R/'figure_data/heat_treatment_path_edges.csv').open())); st={}\nfor n in ns: st.setdefault(int(n['stage']),[]).append(n)\npos={}\nfor s,a in st.items():\n for i,n in enumerate(a): pos[n['node_id']]=(s*3.3,((len(a)-1)/2-i)*1.45)\nf,ax=plt.subplots(figsize=(13,7.2))\nfor e in es:\n x1,y1=pos[e['source']];x2,y2=pos[e['target']];ax.add_patch(FancyArrowPatch((x1+1.05,y1),(x2-1.05,y2),connectionstyle='arc3,rad=.05',arrowstyle='-',linewidth=.8+.8*float(e['weight']),alpha=.38))\nfor n in ns:\n x,y=pos[n['node_id']];ax.add_patch(FancyBboxPatch((x-1.05,y-.32),2.1,.64,boxstyle='round,pad=.03,rounding_size=.06',fill=False));ax.text(x,y,n['label'],ha='center',va='center',fontsize=8.4,wrap=True)\nfor s,l in enumerate(['Initial state','Solution / anneal','Aging / cooling','Dominant final state']): ax.text(s*3.3,max(y for x,y in pos.values())+1,l,ha='center',fontweight='bold')\nax.text(.01,.01,'3 independent papers | 11 sequences | line width = route count | direct table/text evidence',transform=ax.transAxes,fontsize=9);ax.set_xlim(-1.5,11.4);ax.set_ylim(min(y for x,y in pos.values())-1.1,max(y for x,y in pos.values())+1.5);ax.axis('off');f.tight_layout();o=R/'figures/QM28_F1_heat_treatment_paths_alluvial'\nfor e in ['svg','pdf']:f.savefig(o.with_suffix('.'+e),bbox_inches='tight')\nf.savefig(o.with_suffix('.png'),dpi=600,bbox_inches='tight')''',
 'plot_ht_paired_forest.py':'''import csv\nfrom pathlib import Path\nimport matplotlib.pyplot as plt\nR=Path(__file__).resolve().parents[1];a=list(csv.DictReader((R/'figure_data/ht_paired_forest.csv').open()));f,ax=plt.subplots(figsize=(10.5,7.2));ys=list(range(len(a)))[::-1]\nfor y,r in zip(ys,a):\n x=float(r['delta_UTS_MPa']);ax.errorbar(x,y,xerr=[[x-float(r['ci_low'])],[float(r['ci_high'])-x]],fmt='o',capsize=3) if r['ci_low'] else ax.plot(x,y,'o')\nax.axvline(0);ax.set_yticks(ys,[r['label'] for r in a]);ax.set_xlabel('Paired heat-treatment effect on UTS, ΔUTS (MPa)');ax.set_title('Same-paper heat-treatment effects at 600 °C');ax.grid(axis='x',alpha=.25);ax.text(.01,-.12,'k=2 papers; 7 route pairs. Individual uncertainty unavailable; summary CI = discrete paper-cluster bootstrap. Prediction interval not identifiable.',transform=ax.transAxes,fontsize=8.7);f.tight_layout();o=R/'figures/QM28_F2_ht_paired_effect_forest'\nfor e in ['svg','pdf']:f.savefig(o.with_suffix('.'+e),bbox_inches='tight')\nf.savefig(o.with_suffix('.png'),dpi=600,bbox_inches='tight')''',
 'plot_ttc_response.py':'''import csv,math\nfrom pathlib import Path\nimport matplotlib.pyplot as plt\nR=Path(__file__).resolve().parents[1];a=list(csv.DictReader((R/'figure_data/ttc_response_observations.csv').open()));f,ax=plt.subplots(figsize=(10.5,7.2))\nfor r in a:\n if r['property']!='UTS':continue\n c=r['solution_cooling']+'+'+r['aging_cooling'];x=float(r['aging_temperature_C']);y=math.log10(float(r['aging_time_min']));v=float(r['delta_effect']);ax.scatter(x,y,s=45+abs(v)*.38,marker='s' if c=='WQ+AC' else 'o',alpha=.72);ax.text(x+5,y+.015,f'{v:+.0f} MPa\\n{r["test_temperature_C"]}°C test',fontsize=8)\nax.set_xlabel('Aging temperature (°C)');ax.set_ylabel('log10 aging time (min)');ax.set_title('Observed T–t–cooling support map for ΔUTS');ax.text(.01,.02,'Circle AC+AC; square WQ+AC. Bubble size ∝ |ΔUTS|. No interpolated surface: time, cooling, matrix and solution state are confounded.',transform=ax.transAxes,fontsize=8.7);ax.grid(alpha=.22);f.tight_layout();o=R/'figures/QM28_F3_temperature_time_cooling_response'\nfor e in ['svg','pdf']:f.savefig(o.with_suffix('.'+e),bbox_inches='tight')\nf.savefig(o.with_suffix('.png'),dpi=600,bbox_inches='tight')''',
 'plot_ht_reinforcement_interaction.py':'''import csv\nfrom pathlib import Path\nimport matplotlib.pyplot as plt\nR=Path(__file__).resolve().parents[1];a=list(csv.DictReader((R/'figure_data/ht_reinforcement_interaction.csv').open()));f,ax=plt.subplots(figsize=(9.2,6.8))\nfor g in sorted(set(r['reinforcement'] for r in a)):\n q=sorted([r for r in a if r['reinforcement']==g],key=lambda r:0 if r['state']=='As-built' else 1);ax.plot([0,1],[float(r['rupture_time_h']) for r in q],marker='o',label=g)\n for x,r in enumerate(q):ax.text(x,float(r['rupture_time_h'])+.15,f'{float(r["rupture_time_h"]):.1f} h',ha='center',fontsize=9)\nax.set_xticks([0,1],['As-built','1050 °C / 2 h / furnace cooled']);ax.set_ylabel('Creep rupture time at 600 °C, 200 MPa (h)');ax.set_title('Heat treatment × TiB reinforcement interaction');ax.legend(frameon=False);ax.grid(axis='y',alpha=.25);ax.text(.01,.02,'2×2: Ti64 HT = −2.8 h; TMC HT = +2.9 h; interaction = +5.7 h; ratio-of-ratios = 11.33. No replicate-level CI.',transform=ax.transAxes,fontsize=8.7);f.tight_layout();o=R/'figures/QM28_F4_ht_reinforcement_interaction'\nfor e in ['svg','pdf']:f.savefig(o.with_suffix('.'+e),bbox_inches='tight')\nf.savefig(o.with_suffix('.png'),dpi=600,bbox_inches='tight')'''}
 for n,c in plots.items(): wt(PC/n,'#!/usr/bin/env python3\n'+c); subprocess.run([sys.executable,str(PC/n)],check=True,cwd=PKG)
 ps={'window_id':'QM28','snapshot_id':SNAP,'plots':[{'plot_id':'QM28_F1','title':'Heat-treatment paths alluvial','data':['figure_data/heat_treatment_path_nodes.csv','figure_data/heat_treatment_path_edges.csv'],'code':'plot_code/plot_heat_treatment_alluvial.py','outputs':[f'figures/QM28_F1_heat_treatment_paths_alluvial.{e}' for e in ['svg','pdf','png']],'independent_papers':3,'effect_definition':'route counts/phase transitions','uncertainty':'not applicable','evidence_layer':'direct table/text','support_domain':'three opened primary papers'},{'plot_id':'QM28_F2','title':'HT paired forest','data':['figure_data/ht_paired_forest.csv'],'code':'plot_code/plot_ht_paired_forest.py','outputs':[f'figures/QM28_F2_ht_paired_effect_forest.{e}' for e in ['svg','pdf','png']],'independent_papers':2,'samples':14,'effect_definition':'ΔUTS=HT-baseline at 600C','uncertainty':'cluster bootstrap only for k=2 summary','evidence_layer':'direct table/text','support_domain':'near-alpha TiBw composites'},{'plot_id':'QM28_F3','title':'T-t-cooling support map','data':['figure_data/ttc_response_observations.csv'],'code':'plot_code/plot_ttc_response.py','outputs':[f'figures/QM28_F3_temperature_time_cooling_response.{e}' for e in ['svg','pdf','png']],'independent_papers':2,'effect_definition':'observed ΔUTS by full sequence','uncertainty':'no interpolation; arm variance absent','evidence_layer':'direct table/text','support_domain':'500-750C aging, 60-300min, AC/WQ'},{'plot_id':'QM28_F4','title':'HT x reinforcement interaction','data':['figure_data/ht_reinforcement_interaction.csv'],'code':'plot_code/plot_ht_reinforcement_interaction.py','outputs':[f'figures/QM28_F4_ht_reinforcement_interaction.{e}' for e in ['svg','pdf','png']],'independent_papers':1,'samples':4,'effect_definition':'2x2 DID on rupture time','uncertainty':'replicate variance absent','evidence_layer':'direct Table 2','support_domain':'LPBF Ti64/TiB-Ti64, 600C 200MPa'}]}; wj(PKG/'PLOT_SPECS.json',ps)
 wt(PKG/'00_EXECUTIVE_VERDICT.md',f'''# QM28 Executive Verdict\n\n`WINDOW=QM28 | SNAPSHOT={SNAP} | INPUT_MODE=QUANT_EXECUTE/COHORT_BUILD`\n\nHeat treatment is not a portable scalar in Ti/TMCs. The complete sequence, beta-transus relation, cooling path, metastable matrix state, precipitates and reinforcement-mediated grain-boundary transformation jointly determine the sign.\n\nThree primary papers yielded {len(obs)} atomic rows and {len(pairs)} class-A same-paper pairs. In 2018 extruded 5.1 vol% TiBw/near-alpha Ti, four routes raised 600 °C UTS 850→904-986 MPa (+6.4% to +16.0%) while elongation fell 15.5→14.5-10.8%. In 2024 rolled 3.5 vol% TiB/(TA15-Si), 1050 °C/30 min/WQ+600 °C/1 h/AC produced the optimum 600 °C UTS 710→992 MPa (+282 MPa; +39.7%) and hardness 422→482 HV, but strain fell 39→26%. At 700-750 °C aging, martensite decomposed and abnormal alpha growth reduced the UTS gain to +142/+58 MPa; 750 °C aging reduced hardness below as-rolled. At 700 °C test, UTS rose 228→399-421 MPa while strain fell 182→68%.\n\nThe decisive interaction is the 2021 LPBF 2×2: 1050 °C/2 h/FC changed rupture time 3.4→0.6 h in Ti64 but 2.9→5.8 h in TiB/Ti64. Additive HT×reinforcement interaction = +5.7 h; ratio-of-ratios = 11.33. Continuous GB-alpha explains Ti64 collapse; TiB suppresses that network and adds equiaxed alpha, interfaces and load transfer.\n\nPaper-equal descriptive ΔUTS at 600 °C across two tensile paper families = {eq:.1f} MPa; discrete k=2 cluster interval {lo:.1f}-{hi:.1f} MPa. Formal random effects/prediction interval are NOT_IDENTIFIABLE; LOPO range {min(pm.values()):.1f}-{max(pm.values()):.1f} MPa.\n\nClaim ceiling: level 2, same-paper paired association/controlled 2×2 interaction. No ACTIVE/Gold mutation, production-model registration, platform retraining or VALIDATED formulation. Structurally complete for opened evidence; canonical V29 archive ingestion remains a data gap.''')
 wt(PKG/'METHODS.md',f'''# Methods\n\nAtomic unit: paper × sample × actual composition × precursor/reinforcement × process × ordered heat-treatment sequence × microstructure × test mode/temperature/stress/rate/orientation × property. No route was collapsed to maximum temperature.\n\nEstimands: ΔY=Y_HT−Y_baseline; lnRR=ln(Y_HT/Y_baseline); percent change; additive and multiplicative HT×reinforcement interaction. All pairs are class A. Individual CIs were not fabricated because arm SD/SE is absent. The 600 °C UTS summary averages routes within paper, papers equally, then uses 20,000 paper-cluster bootstrap draws (seed {SEED}); k=2 makes the interval discrete/exploratory and prediction intervals/tau²/I² not identifiable. LOPO equals leave-family-out here.\n\nDose variables preserve temperature, time, cooling and beta-transus relation. Only observed points are plotted; no unsupported interpolation. The 2021 2×2 DID is an association, not randomized causality. No p-value family was generated, so BH-FDR is not applicable. Plot scripts read figure_data CSVs and emit SVG/PDF/600 dpi PNG.''')
 wt(PKG/'LIMITATIONS.md','''# Limitations\n\n1. Canonical V29 atomic/provenance/condition assets and uploaded archive bytes were not accessible because the execution backend rejected archive sessions; this is a derived, non-authoritative snapshot.\n2. Three independent quantitative papers; two comparable tensile families. Formal hierarchical/dose models are not identifiable.\n3. Original byte hashes are missing for File Library PDFs; normalized capture hashes are typed explicitly.\n4. Arm SD/SE is absent; point contrasts have no fabricated CI.\n5. 2018 500/550 °C caption conflict is preserved; Table 1 is authoritative.\n6. 2024 750 °C-aged elongation is missing; no imputation/digitization.\n7. Exact relative beta-transus is available only for 2024 (+30 °C); cooling rates are labels, not measured rates.\n8. Creep interaction is specific to LPBF Ti64/TiB-Ti64 at 600 °C/200 MPa.\n9. Claim level ≤2; no Gold/ACTIVE/model/formulation promotion.''')
 req={'window_id':'QM28','current_snapshot_id':SNAP,'status':'CONTINUE_DATA_GAP','required_inputs':[{'name':'V29_ATOMIC_RECORDS','patterns':['**/ATOMIC_RECORDS.csv','**/ATOMIC_RECORDS.parquet'],'reason':'authoritative cohort/all pairs'},{'name':'V29_PROVENANCE','patterns':['**/PROVENANCE.jsonl'],'reason':'original hashes/locators'},{'name':'CONDITION_MANIFEST','patterns':['**/condition_canonical_manifest*.csv'],'reason':'full route/cooling normalization'},{'name':'SOURCE_RELIABILITY','patterns':['**/source_reliability*.csv','**/quality_domain*.csv'],'reason':'evidence weighting'},{'name':'PAPER_REGISTRY','patterns':['**/paper*registry*.csv'],'reason':'duplicate control'},{'name':'REPLICATE_UNCERTAINTY','patterns':['**/*replicate*.csv','**/*uncertainty*.csv'],'reason':'CI/hierarchical model'},{'name':'ORIGINAL_BYTE_HASHES','patterns':['**/CHECKSUMS.sha256','**/MANIFEST.json'],'reason':'replace normalized capture hashes'}],'archives_to_scan':['/mnt/data/'+n for n in archives],'minimum_required_fields':['snapshot_id','source_hash','paper_uid','sample_uid','condition_uid','full_heat_treatment_sequence','beta_transus_C','cooling_rate_or_label','property','value','unit','test_temperature_C','test_mode','replicate_n','sd_or_se'],'local_actions':['CRC/testzip/SHA all archives without repacking','extract canonical QM28 rows','rerun recompute/tests/plots','do not promote ACTIVE/Gold until closure']}; wj(PKG/'WEB_TO_LOCAL_REQUEST.json',req)
 wt(PKG/'LOCAL_ABSORPTION_PROMPT.md',f'''# Local absorption prompt — QM28\n\nVerify ZIP CRC and `sha256sum -c CHECKSUMS.sha256`. Preserve source archives unchanged. Resolve `WEB_TO_LOCAL_REQUEST.json` against V29; replace normalized hashes with original byte SHA and bind every row to snapshot/source/paper/sample/condition. Merge only into `q40/QM28`; do not modify ACTIVE_TITMC, Gold, Schema or model registry. Run `python analysis_code/recompute_qm28.py`, unit tests and four plot scripts. Compare rows/estimands/figure-data hashes; never overwrite conflicts silently. Current derived snapshot: `{SNAP}`.''')
 wt(PKG/'DATA_DICTIONARY.md','''# Data dictionary\n\n`sequence_uid` preserves ordered stages; `delta` is treated−baseline; `lnRR` is log treated/baseline; `match_class=A` is strict same-paper matching; `claim_level≤2`; `support_domain` bounds transfer; `source_hash` is typed original-byte or normalized-capture SHA.''')
 wt(PKG/'README.md',f'# FINAL_QM28\n\nWindow QM28; snapshot `{SNAP}`; 4 papers seen, 3 included, {len(obs)} atomic rows, {len(pairs)} pairs, 4 logical plots/12 files, claim level 2, status `CONTINUE_DATA_GAP`. Start with `00_EXECUTIVE_VERDICT.md`, `METHODS.md`, `WINDOW_STATUS.json`, `WEB_TO_LOCAL_REQUEST.json`.')
 # status before tests
 status={'window_id':'QM28','snapshot_id':SNAP,'generated_at':NOW,'papers_seen':4,'papers_included':3,'independent_papers':3,'atomic_rows':len(obs),'matched_pairs':len(pairs),'effect_estimates':len(effects),'plots_generated':4,'plot_files_generated':12,'open_conflicts':sum(c['status'].startswith('OPEN') for c in conf),'claim_level_max':2,'status':'CONTINUE_DATA_GAP','next_action':'Ingest canonical V29 atomic/provenance/condition assets and original byte hashes; rerun.','production_model_registered':False,'active_mutated':False,'gold_promoted':False}; wj(PKG/'WINDOW_STATUS.json',status)
 # recompute/test
 wt(AC/'recompute_qm28.py','''import csv,math\nfrom pathlib import Path\nR=Path(__file__).resolve().parents[1]\ndef rd(n):\n with (R/n).open() as f:return list(csv.DictReader(f))\na=rd('HT_PAIR_EFFECTS.csv')\nfor r in a:\n b=float(r['baseline_value']);t=float(r['treated_value']);assert abs(float(r['delta'])-(t-b))<1e-8;assert abs(float(r['lnRR'])-math.log(t/b))<1e-7\ni=next(x for x in rd('HT_REINFORCEMENT_INTERACTIONS.csv') if x['outcome']=='creep_rupture_time');assert abs(float(i['additive_interaction'])-5.7)<1e-9;assert abs(float(i['ratio_of_ratios'])-11.333333333333334)<1e-8\nprint({'pass':True,'pairs_checked':len(a)})''')
 wt(TS/'test_qm28.py','''import csv,json,unittest\nfrom pathlib import Path\nR=Path(__file__).resolve().parents[1]\nclass T(unittest.TestCase):\n def test_required(self):\n  q=['00_EXECUTIVE_VERDICT.md','INPUT_LEDGER.csv','ANALYSIS_COHORT.csv','PAIR_MATCHES.csv','EFFECT_ESTIMATES.csv','HIERARCHICAL_RESULTS.csv','DOSE_RESPONSE.csv','INTERACTION_EFFECTS.csv','HETEROGENEITY.csv','SENSITIVITY_ANALYSIS.csv','NULL_NEGATIVE_RESULTS.csv','CONFLICT_LEDGER.csv','PROVENANCE.jsonl','METHODS.md','LIMITATIONS.md','PLOT_SPECS.json','WEB_TO_LOCAL_REQUEST.json','LOCAL_ABSORPTION_PROMPT.md','WINDOW_STATUS.json','HEAT_TREATMENT_SEQUENCES.csv','HT_PAIR_EFFECTS.csv','HT_DOSE_RESPONSE.csv','HT_REINFORCEMENT_INTERACTIONS.csv'];self.assertTrue(all((R/x).exists() for x in q))\n def test_pairs(self):\n  a=list(csv.DictReader((R/'HT_PAIR_EFFECTS.csv').open()));self.assertEqual(len(a),30);[self.assertAlmostEqual(float(x['delta']),float(x['treated_value'])-float(x['baseline_value']),7) for x in a]\n def test_interaction(self):\n  a=list(csv.DictReader((R/'HT_REINFORCEMENT_INTERACTIONS.csv').open()));x=next(r for r in a if r['outcome']=='creep_rupture_time');self.assertAlmostEqual(float(x['additive_interaction']),5.7,7)\n def test_plots(self):\n  a=json.loads((R/'PLOT_SPECS.json').read_text());self.assertEqual(len(a['plots']),4);[self.assertTrue((R/x).exists()) for p in a['plots'] for x in p['outputs']]\n def test_no_nested_zip(self):self.assertEqual(list(R.rglob('*.zip')),[])\n def test_ceiling(self):\n  s=json.loads((R/'WINDOW_STATUS.json').read_text());self.assertLessEqual(s['claim_level_max'],2);self.assertEqual(s['status'],'CONTINUE_DATA_GAP')\n''')
 rr=subprocess.run([sys.executable,str(AC/'recompute_qm28.py')],cwd=PKG,capture_output=True,text=True,check=True); tt=subprocess.run([sys.executable,'-m','unittest','discover','-s',str(TS),'-v'],cwd=PKG,capture_output=True,text=True); wt(PKG/'self_test_output.txt',tt.stdout+'\n'+tt.stderr+f'\npass={str(tt.returncode==0).lower()}'); assert tt.returncode==0; wt(PKG/'RUN_LOG.txt',f'generated_at={NOW}\nsnapshot={SNAP}\n{rr.stdout.strip()}\nlogical_plots=4\nplot_files=12')
 # manifest/checksums
 files=[]
 for p in sorted(PKG.rglob('*')):
  if p.is_file() and p.name not in ['MANIFEST.json','CHECKSUMS.sha256']: files.append({'path':p.relative_to(PKG).as_posix(),'bytes':p.stat().st_size,'sha256':shab(p.read_bytes())})
 wj(PKG/'MANIFEST.json',{'window_id':'QM28','snapshot_id':SNAP,'generated_at':NOW,'status':'CONTINUE_DATA_GAP','claim_level_max':2,'seed':SEED,'counts':{'papers_seen':4,'papers_included':3,'atomic_rows':len(obs),'matched_pairs':len(pairs),'effect_estimates':len(effects),'sequences':len(seq),'logical_plots':4},'files':files,'constraints':{'nested_zip':False,'production_model_registration':False,'active_mutation':False,'gold_promotion':False}})
 val={'pass':True,'required_files_present':True,'logical_plots':4,'plot_files':len(list(FG.glob('*'))),'figure_data_files':len(list(FD.glob('*.csv'))),'plot_code_files':len(list(PC.glob('*.py'))),'matched_pairs':len(pairs),'independent_papers':3,'no_nested_zip':not any(PKG.rglob('*.zip')),'formal_hierarchical_model':'NOT_IDENTIFIABLE','status':'CONTINUE_DATA_GAP'}; wj(PKG/'VALIDATION_REPORT.json',val)
 wt(PKG/'CHECKSUMS.sha256','\n'.join(f'{shab(p.read_bytes())}  {p.relative_to(PKG).as_posix()}' for p in sorted(PKG.rglob('*')) if p.is_file() and p.name!='CHECKSUMS.sha256'))
 z=BUILD/'FINAL_QM28.zip'
 with zipfile.ZipFile(z,'w',zipfile.ZIP_DEFLATED,compresslevel=9) as a:
  for p in sorted(PKG.rglob('*')):
   if p.is_file(): a.write(p,(Path('FINAL_QM28')/p.relative_to(PKG)).as_posix())
 with zipfile.ZipFile(z) as a: assert a.testzip() is None and not any(n.lower().endswith('.zip') for n in a.namelist())
 wt(BUILD/'FINAL_QM28.sha256',f'{shab(z.read_bytes())}  FINAL_QM28.zip')
 print(json.dumps({'window':'QM28','snapshot':SNAP,'zip':str(z),'sha256':shab(z.read_bytes()),'status':'CONTINUE_DATA_GAP'},ensure_ascii=False))
if __name__=='__main__':build()
